### ISSUE TITLE
Use bulloak in github workflow

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/flow#174]
Since https://github.com/alexfertel/bulloak/pull/68 has been merged, Bulloak can now be used in the github workflow to verify the specs of the concrete tests. Thus, we should add a new workflow file to run checks using bulloak on every PR.

<details> <summary>bulloak.yml code</summary>

```yml
name: "Verify the specs of concrete tests using bulloak"

on: "workflow_call"

jobs:
  bulloak-check:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Cache cargo"
        id: cache-cargo
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: "Install Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"

      - name: "Install bulloak"
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: "cargo install bulloak"

      - name: "Verify the concrete tests"
        run: "bulloak check test/integration/concrete/**/**.tree --skip-modifiers"

      - name: "Bulloak summary"
        run: |
          echo "## Bulloak result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
```
</details>

### Note

Since lockup repo does not use Bulloak yet, we can just add it to this repo instead of [reusable-workflow](https://github.com/sablier-labs/reusable-workflows). Once lockup repo has been refactored to use bulloak, we can add it to reusable-workflow repo.
